import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased h-screen w-screen flex flex-col overflow-hidden`}
      >
        <Navbar />
        <div className="flex flex-1 h-[calc(100vh-60px)] w-full">
          <Sidebar />
          <div className="flex-1 h-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
